### ISSUE TITLE
update the composer config

### ISSUE THREAD

**Issue by v-leonhou** [kenjis/ci-app-for-ci-phpunit-test#10]
![qq 20170206115046](https://cloud.githubusercontent.com/assets/8463045/22634188/8212fe1c-ec62-11e6-9555-c1eed05ef5a2.png)

**Comment by kenjis** [comment]
It seems [satooshi/php-coveralls](https://github.com/satooshi/php-coveralls) depends on it.

```
satooshi/php-coveralls v1.0.1 PHP client library for Coveralls API
├──ext-json *
├──ext-simplexml *
├──guzzle/guzzle ^2.8|^3.0
│  ├──ext-curl *
│  ├──php >=5.3.3
│  └──symfony/event-dispatcher ~2.1
│     └──php >=5.3.9
```

**Comment by v-leonhou** [comment]
yes,so  update the composer config? the name seem to be changed

**Comment by kenjis** [comment]
No. `php-coveralls` 1.0 depends on `guzzle/guzzle`.
We have to wait for php-coveralls 2.0 release. See <https://github.com/satooshi/php-coveralls/issues/203>.

**Comment by v-leonhou** [comment]
get it，thanks
