### ISSUE TITLE
my-codeigniter.sh -> composer update failed

### ISSUE THREAD

**Issue by adampweb** [kenjis/ci-app-for-ci-phpunit-test#13]
**error**:
**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - deployer/deployer v3.0.10 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.0.11 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.0.7 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.0.8 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.0.9 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.1.0 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.1.1 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.1.2 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.2.0 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.2.1 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - deployer/deployer v3.3.0 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.x-dev].
    - **Conclusion**: don't install phpseclib/phpseclib 2.0.x-dev
    - Installation request for kenjis/codeigniter-deployer 1.0.x@dev -> satisfiable by kenjis/codeigniter-deployer[1.0.x-dev].
    - **Conclusion**: don't install symfony/config v4.0.3|install deployer/deployer v3.0.10|install deployer/deployer v3.0.11|install deployer/deployer v3.0.7|install deployer/deployer v3.0.8|install deployer/deployer v3.0.9|install deployer/deployer v3.1.0|install deployer/deployer v3.1.1|install deployer/deployer v3.1.2|install deployer/deployer v3.2.0|install deployer/deployer v3.2.1|install deployer/deployer v3.3.0
    - **Conclusion**: remove symfony/config v4.0.3|install deployer/deployer v3.0.10|install deployer/deployer v3.0.11|install deployer/deployer v3.0.7|install deployer/deployer v3.0.8|install deployer/deployer v3.0.9|install deployer/deployer v3.1.0|install deployer/deployer v3.1.1|install deployer/deployer v3.1.2|install deployer/deployer v3.2.0|install deployer/deployer v3.2.1|install deployer/deployer v3.3.0

**Comment by kenjis** [comment]
@adampweb Thank you for your report.
But `my-codeigniter.sh` is from <https://github.com/kenjis/codeigniter-composer-installer>.

Would you please report it to <https://github.com/kenjis/codeigniter-composer-installer>?
