### ISSUE TITLE
How to i use the inside tests/models file ? i got an error.

### ISSUE THREAD

**Issue by ganesh98a** [kenjis/ci-app-for-ci-phpunit-test#24]
Can you pls help me solve this error. i can't work with inside models file of tests folder.
Code
```class Auth_test extends TestCase
{
    protected $CI; 	
    public function setUp() { 	
        $this->CI = &get_instance();
        $this->obj = $this->newModel('Auth_model');
    }
}
```

Error

PHPUnit 6.5.12 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

E..                                                                 3 / 3 (100%)G:\xampp\htdocs\hcm\admin\back-end\application

Time: 433 ms, Memory: 6.00MB

There was 1 error:

1) Auth_test::testLoginTrue
Error: Call to undefined method Auth_test::newModel()

**Comment by kenjis** [comment]
@ganesh98a See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#unittestcasenewmodelclassname

Your code does not contain where the error causes.
So I don't know why you have such an error.

And this is the repository for testing. If you have questions
about how to use ci-phpunit-test, create an issue on
<https://github.com/kenjis/ci-phpunit-test/issues>, please.
